es:
  host: '192.168.0.105'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

db:
  host: '192.168.0.101'
  port: 3306
  user: 'dev'
  password: 'password'
  name: 'municipality'

consumer:
  brokers: ['192.168.0.105:9092']
  topic: 'store.municipality.superhero'
  group_id: 'consumer-register-group'

cache:
  address: '192.168.0.105'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  token_key_format: 'token.%s'

health:
  address: '192.168.0.101'
  port: ':8080'
  shutdown_endpoint: '/api/v1/consumer_superhero_register_health/shutdown'
  content_type: 'application/json'