es:
  host: '192.168.178.17'
  port: '9200'
  cluster: 'superheromatch'
  index: 'superhero'

db:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'Kolian18**'
  name: 'municipality'

consumer:
  brokers: ['192.168.178.17:9092']
  topic: 'store.municipality.superhero'
  group_id: 'consumer-register-group'

cache:
  address: '192.168.178.17'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  token_key_format: 'token.%s'